repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer    # Ensure files end with a newline
      - id: check-yaml           # Validate YAML files
      - id: check-json           # Validate JSON files
      - id: check-added-large-files  # Prevent committing large files

  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
      - id: black  # Format Python code with Black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort  # Sort Python imports

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8  # Python code linting with Flake8
        args: [--max-line-length=88]  # Match Black's default line length

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy  # Static type checking with Mypy
        args: [--ignore-missing-imports]
